site_name: Rybook
site_description: A field book by a guy in the field
site_author: Ryan W Walter
site_url: 'https://blackphidora.gitlab.io/rybook'
repo_url: 'https://gitlab.com/Blackphidora/rybook'
repo_name: 'Rybook: CE Edition'

# Nagication
nav:
    - Home:
      - Linux:
        - LVM Caching: linux/lvm/lvmcache.md;

