site_name: Rybook
site_description: A field book by a guy in the field
site_author: Ryan W Walter
site_url: 'https://blackphidora.gitlab.io/rybook'
repo_url: 'https://gitlab.com/Blackphidora/rybook'
repo_name: 'Rybook'
theme: readthedocs
# navigation
nav:
    - Home: index.md
    - Linux:
      - Booting:
        - IPXE: linux/ipxe.md
      - Kickstart: linux/kickstart/whatiskickstart.md
      - LVM:
        - What is LVM: linux/lvm/whatislvm.md
        - LVM Caching: linux/lvm/lvmcache.md
      - Kernel:
        - NCQ: linux/kernel/NCQ.md
    - Windows:
      - Tidbits: windows/tidbits.md
      - Run Prompt Shortcuts: windows/shortcuts.md
      - Trendmicro: windows/Trendmicro.md
    - Tools: 
      - Software: tools/software.md
      - Hardware: tools/hardware.md
    - Checklists: meta/checklists.md
    - Meta:
      - Maintaining the Meatbag: meta/maintthemeatbag.md

    - 'About Me': meta/aboutme.md
